config/routes.rb
Textrv::Application.routes.draw do

  root to: 'systems#index'
  resources :system_requirements

  resources :systems do
    get 'validate', on: :member
    get 'analyze', on: :member
  end

  resources :properties

  resources :entities

  resources :models

end

app/models/system.rb
class System < ActiveRecord::Base
  attr_accessor :validation, :analysis

  belongs_to :model
  belongs_to :entity
  has_many :system_requirements

  accepts_nested_attributes_for :system_requirements

  after_initialize do |system|
    system.validation = {}
    system.analysis = {}
  end

  def validate
    self.analyze
    self.validation[:validated] = true
    self.validation[:verified] = self.entity.properties_array & self.analysis[:all_nouns]
    self.validation[:unverified] = self.entity.properties_array - self.analysis[:all_nouns]
  end

  def analyze
    # Write to a temporary file all the system requirements. This file is read by the python script
    File.open('tmp/text_corpora.txt', 'w') do |f|
      self.system_requirements.each do |sys_req|
        f.puts sys_req.title
        f.puts sys_req.description
      end
    end

    output = %x(python -c 'import imp; analyzer = imp.load_source("analyze", "scripts/analyze.py"); analyzer.basics("tmp/text_corpora.txt")')
    self.analysis[:text_description] = {}
    output.each_line do |line|
      out_array = line.delete("\n").split('=>')
      self.analysis[:text_description][out_array[0]] = out_array[1]
    end

    output = %x(python -c 'import imp; analyzer = imp.load_source("analyze", "scripts/analyze.py"); analyzer.nouns("tmp/text_corpora.txt")')
    output.concat %x(python -c 'import imp; analyzer = imp.load_source("analyze", "scripts/analyze.py"); analyzer.noun_phrases("tmp/text_corpora.txt")')

    p output
    self.analysis[:nouns] = {}
    self.analysis[:all_nouns] = []
    output.each_line do |line|
      out_array = line.delete("\n").split('=>')
      # The use of eval below is insanely dangerous. We're evaluating whatever we got from the python script.
      # Here we're trusting that we got an array
      self.analysis[:nouns][out_array[0]] = eval(out_array[1])
      self.analysis[:all_nouns].concat eval(out_array[1])
    end

    self.analysis[:analyzed] = true
  end
end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
  before_action :set_system, only: [:show, :edit, :update, :destroy, :validate, :analyze]

  def validate
    logger.debug "Validating"
    @system.validate
    render "show"
  end

  def analyze
    logger.debug "Analyzing"
    @system.analyze
    render "show"
  end

  # GET /systems
  # GET /systems.json
  def index
    @systems = System.all
  end

  # GET /systems/1
  # GET /systems/1.json
  def show
  end

  # GET /systems/new
  def new
    @system = System.new
  end

  # GET /systems/1/edit
  def edit
  end

  # POST /systems
  # POST /systems.json
  def create
    @system = System.new(system_params)

    respond_to do |format|
      if @system.save
        format.html { redirect_to @system, notice: 'System was successfully created.' }
        format.json { render action: 'show', status: :created, location: @system }
      else
        format.html { render action: 'new' }
        format.json { render json: @system.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /systems/1
  # PATCH/PUT /systems/1.json
  def update
    respond_to do |format|
      if @system.update(system_params)
        format.html { redirect_to @system, notice: 'System was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @system.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /systems/1
  # DELETE /systems/1.json
  def destroy
    @system.destroy
    respond_to do |format|
      format.html { redirect_to systems_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_system
      @system = System.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def system_params
      params.require(:system).permit(:model_id, :entity_id, :name, system_requirements_attributes: [ :title, :description, :system_id, :id ])
    end
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/views/systems/_form.html.erb
<%= semantic_form_for @system do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :model %>
    <%= f.input :entity %>
    <%= f.inputs :title, :for => :system_requirements, :name => "System Requirements" %>
  <% end %>
  <%= f.actions %>
<% end %>

app/views/systems/edit.html.erb
<%- model_class = System -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/systems/index.html.erb
<%- model_class = System -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:model_id) %></th>
      <th><%= model_class.human_attribute_name(:entity_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @systems.each do |system| %>
      <tr>
        <td><%= link_to system.id, system_path(system) %></td>
        <td><%= system.name %></td>
        <td><%= system.model.name %></td>
        <td><%= system.entity.name %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_system_path(system), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      system_path(system),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_system_path,
            :class => 'btn btn-primary' %>

app/views/systems/new.html.erb
<%- model_class = System -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/systems/show.html.slim
- model_class = System

.page-header
  h1 = model_class.model_name.human.titleize

dl.dl-horizontal
  dt = model_class.human_attribute_name(:name)
  dd = @system.name
  dt = model_class.human_attribute_name(:model_id)
  dd = @system.model.name
  dt = model_class.human_attribute_name(:entity_id)
  dd = @system.entity.name
  dt = model_class.human_attribute_name(:properties)
  - @system.entity.properties.each do |prop|
    dd = prop.name
  dt = model_class.human_attribute_name(:system_requirements)
  - @system.system_requirements.each do |req|
    dd = req.title

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), systems_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_system_path(@system), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")),
    system_path(@system),
    :method => 'delete',
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
    :class => 'btn btn-danger'
  = link_to 'Analyze', analyze_system_path(@system), :class => 'btn btn-info'
  = link_to 'Validate', validate_system_path(@system), :class => 'btn btn-success'

- if @system.validation[:validated]
  .span6
    h3 System Validation
    table.table.table-striped.table-bordered.table-hover
      tr
        td Verified properties
        td
          - @system.validation[:verified].each do |v|
            span.label.label-success.noun = v
      tr
        td Unverified properties
        td
          - @system.validation[:unverified].each do |v|
            span.label.label-important.noun = v

- if @system.analysis[:analyzed]
  .span6
    h3 Basic Properties
    table.table.table-striped.table-bordered.table-hover
      thead
        <tr><th>Property</th><th>Value</th></tr>
      tbody
        - @system.analysis[:text_description].each do |key, value|
          tr
            td = model_class.human_attribute_name key
            td = value
    h3 Objects
    table.table.table-striped.table-bordered.table-hover
      - @system.analysis[:nouns].each do |key, value|
        tr
          td = key
          td
            - value.each do |v|
              span.label.noun = v