config/routes.rb
Textrv::Application.routes.draw do

  root to: 'systems#index'
  resources :system_requirements

  resources :systems do
    get 'validate', on: :member
    get 'analyze', on: :member
  end

  resources :properties

  resources :entities

  resources :models

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Textrv</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<a href="https://github.com/aarellano/textrv"><img style="position: absolute; top: 0; right: 0; border: 0; z-index: 9999;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_green_007200.png" alt="Fork me on GitHub"></a>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">TextReq Validation</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Systems", systems_path %></li>
            <li><%= link_to "Requirements", system_requirements_path %></li>
            <li><%= link_to "Models", models_path %></li>
            <li><%= link_to "Entities", entities_path %></li>
            <li><%= link_to "Properties", properties_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>